window.cartReady='started';const storyCanvas=document.querySelector('#storyCanvas'),storyCtx=storyCanvas.getContext('2d'),openingCanvas=document.querySelector('#openingCanvas'),openingCtx=openingCanvas.getContext('2d');
const frameCount=50,storyImages=[],openingImages=[];let storyFrame=0,openingFrame=0;
const openingChapters=[['Care that<br><em>becomes</em><br>a ritual.','Scroll slowly. This is a space made for your becoming.'],['For the days<br>you need<br><em>holding.</em>','Thoughtful essentials, designed to soften the moments that matter.'],['A future that<br>feels <em>gentler.</em>','The things that matter, gathered close — one chapter at a time.'],['Welcome to<br><em>Aanchal.</em>','Care that holds you, through every becoming.']];
const storyChapters=[['The quiet<br><em>beginning.</em>','A new rhythm begins — full of possibility, questions, and small moments of wonder.'],['Made for<br><em>the waiting.</em>','A little more preparation. A little more tenderness. Room for both anticipation and rest.'],['A softer<br><em>arrival.</em>','A new world, held close. The essential things, gathered with care for the day you finally meet.'],['Together, in<br><em>every season.</em>','Because care does not end at arrival. It grows with you, one gentle day at a time.']];
for(let i=1;i<=frameCount;i++){let s=new Image(),o=new Image();s.src=`newframes/ezgif-frame-${String(i).padStart(3,'0')}.jpg`;o.src=`imgframes/ezgif-frame-${String(i).padStart(3,'0')}.jpg`;storyImages.push(s);openingImages.push(o)}
function paint(canvas,ctx,img){if(!img?.complete)return;const d=devicePixelRatio,w=innerWidth*d,h=innerHeight*d;canvas.width=w;canvas.height=h;const scale=Math.max(w/img.width,h/img.height);const iw=img.width*scale,ih=img.height*scale;ctx.clearRect(0,0,w,h);ctx.drawImage(img,(w-iw)/2,(h-ih)/2,iw,ih)}
function resize(){paint(storyCanvas,storyCtx,storyImages[storyFrame]);paint(openingCanvas,openingCtx,openingImages[openingFrame])}openingImages[0].addEventListener('load',resize);storyImages[0].addEventListener('load',resize);addEventListener('resize',resize);
function progressFor(selector){const el=document.querySelector(selector),available=el.offsetHeight-innerHeight;return Math.max(0,Math.min(1,(scrollY-el.offsetTop)/available))}
function updateSequences(){const op=progressFor('.opening-story');openingFrame=Math.min(frameCount-1,Math.floor(op*(frameCount-1)));paint(openingCanvas,openingCtx,openingImages[openingFrame]);const oi=Math.min(3,Math.floor(op*4)),ot=document.querySelector('#openingTitle'),ox=document.querySelector('#openingText');if(ot.dataset.chapter!=oi){ot.dataset.chapter=oi;ot.style.opacity=0;ox.style.opacity=0;setTimeout(()=>{ot.innerHTML=openingChapters[oi][0];ox.textContent=openingChapters[oi][1];ot.style.opacity=1;ox.style.opacity=1},120)}const sp=progressFor('.scroll-story');storyFrame=Math.min(frameCount-1,Math.floor(sp*(frameCount-1)));paint(storyCanvas,storyCtx,storyImages[storyFrame]);const si=Math.min(3,Math.floor(sp*4)),st=document.querySelector('#storyTitle'),sx=document.querySelector('#storyText');if(st.dataset.chapter!=si){st.dataset.chapter=si;st.style.opacity=0;sx.style.opacity=0;setTimeout(()=>{st.innerHTML=storyChapters[si][0];sx.textContent=storyChapters[si][1];st.style.opacity=1;sx.style.opacity=1},120);document.querySelectorAll('.story-progress span').forEach((x,i)=>x.classList.toggle('active',i===si))}}
addEventListener('scroll',updateSequences,{passive:true});updateSequences();
document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.2}).observe(el));
let cart=(()=>{try{return JSON.parse(localStorage.getItem('aanchal-cart')||'[]')}catch(error){return[]}})();
const products={'BirthReady Essential Kit':{price:2499,img:'maincontent/sku1.png'},'Postpartum Recovery Kit':{price:3499,img:'maincontent/sku2.png'},'Postpartum Care Ritual':{price:1899,img:'maincontent/sku3.png'},'Gond Ladoo Recovery Box':{price:1299,img:'maincontent/sku4.png'},'Little One Keepsake Set':{price:1599,img:'maincontent/sku5.png'},'Mustard Seed Baby Pillow':{price:899,img:'maincontent/sku6.png'},'Organic Muslin Swaddle':{price:799,img:'maincontent/sku7.png'},'Baby Welcome Box':{price:2999,img:'maincontent/sku8.png'},'Calm Mother Wellness Candle':{price:999,img:'maincontent/sku9.png'},'Herbal Wellness Candles':{price:1199,img:'maincontent/sku10.png'},"Mother's Wellness Hamper":{price:3999,img:'maincontent/sku11.png'}};
const money=n=>'₹'+n.toLocaleString('en-IN');
function cartTotal(){return cart.reduce((total,item)=>total+item.qty*item.price,0)}
function renderCart(){const box=document.querySelector('.cart-items'),count=cart.reduce((total,item)=>total+item.qty,0);localStorage.setItem('aanchal-cart',JSON.stringify(cart));document.querySelector('.bag i').textContent=count;document.querySelector('.cart-total strong').textContent=money(cartTotal());box.innerHTML=cart.length?cart.map(item=>`<div class="cart-line"><img src="${item.img}" alt="${item.name}"><div><h4>${item.name}</h4><p>${money(item.price)}</p><div class="line-controls"><div class="qty"><button aria-label="Decrease ${item.name}" data-change="-1" data-name="${item.name}">−</button><span>${item.qty}</span><button aria-label="Increase ${item.name}" data-change="1" data-name="${item.name}">+</button></div><button class="remove" data-remove="${item.name}">Remove</button></div></div></div>`).join(''):'<div class="cart-empty"><span>♡</span><h3>Your bag is waiting.</h3><p>Gather the things that will hold you close.</p></div>';box.querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>{const item=cart.find(entry=>entry.name===button.dataset.name);item.qty+=Number(button.dataset.change);if(item.qty<1)cart=cart.filter(entry=>entry!==item);renderCart()});box.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{cart=cart.filter(item=>item.name!==button.dataset.remove);renderCart()})}
function openCart(){document.body.classList.add('cart-open');document.querySelector('.cart-drawer').setAttribute('aria-hidden','false')}
function closeCart(){document.body.classList.remove('cart-open');document.querySelector('.cart-drawer').setAttribute('aria-hidden','true')}
const checkoutModal=document.querySelector('.checkout-modal');
function showCheckoutStep(step){const steps=['details','payment','success'],stepIndex=steps.indexOf(step);document.querySelectorAll('.checkout-step').forEach(section=>section.classList.toggle('active',section.dataset.step===step));document.querySelectorAll('.checkout-steps span').forEach((label,index)=>label.classList.toggle('active',index===stepIndex))}
function openCheckout(){if(!cart.length)return;closeCart();document.querySelector('.checkout-total').textContent=money(cartTotal());showCheckoutStep('details');document.body.classList.add('checkout-open');checkoutModal.setAttribute('aria-hidden','false');checkoutModal.querySelector('input').focus()}
function closeCheckout(){document.body.classList.remove('checkout-open');checkoutModal.setAttribute('aria-hidden','true')}
document.querySelector('.bag').onclick=openCart;document.querySelector('.close-cart').onclick=closeCart;document.querySelector('.cart-scrim').onclick=closeCart;document.querySelectorAll('.add').forEach(button=>button.onclick=()=>{const product=products[button.dataset.product],existing=cart.find(item=>item.name===button.dataset.product);existing?existing.qty++:cart.push({name:button.dataset.product,qty:1,...product});renderCart();openCart()});document.querySelector('.checkout').onclick=openCheckout;document.querySelector('.close-checkout').onclick=closeCheckout;document.querySelector('.checkout-scrim').onclick=closeCheckout;document.querySelector('.checkout-next').onclick=()=>{const form=document.querySelector('#checkoutForm');if(form.querySelector('[data-step="details"]').querySelectorAll(':invalid').length)return form.reportValidity();showCheckoutStep('payment')};document.querySelector('.checkout-back').onclick=()=>showCheckoutStep('details');document.querySelector('#checkoutForm').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;document.querySelector('.success-name').textContent=form.elements.name.value.split(' ')[0];document.querySelector('.success-email').textContent=form.elements.email.value;showCheckoutStep('success');cart=[];renderCart()};document.querySelector('.close-success').onclick=closeCheckout;document.querySelector('.menu').onclick=()=>document.body.classList.toggle('nav-open');document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(document.body.classList.contains('checkout-open'))closeCheckout();else if(document.body.classList.contains('cart-open'))closeCart();else if(document.body.classList.contains('ai-open'))closeAi()});renderCart();window.cartReady='bound';
document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<760)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/24,y=(e.clientY-r.top-r.height/2)/30;card.style.transform=`perspective(1000px) rotateY(${x}deg) rotateX(${-y}deg) scale(1.025)`});card.addEventListener('pointerleave',()=>card.style.transform='')});addEventListener('mousemove',e=>{const g=document.querySelector('.cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});
const aiForm=document.querySelector('#aiForm'),aiInput=document.querySelector('#aiInput'),aiMessages=document.querySelector('#aiMessages');
let pregnancyKnowledge=[];
fetch('pregnancy_baby_qa%20(1).json').then(response=>response.ok?response.json():[]).then(data=>{pregnancyKnowledge=Array.isArray(data)?data:[]}).catch(()=>{});
const aiAnswers=[{terms:['bleed','bleeding','blood','severe pain','chest pain','breathless','breathing','faint','fainted','seizure','vision'],answer:'Please treat this as urgent. Contact your maternity care team or local emergency services now. If you feel unsafe or symptoms are severe, do not wait for a chat reply.'},{terms:['morning sickness','nausea','vomit','throw up','throwing up'],answer:'Nausea is common in pregnancy, especially early on. Small frequent meals, plain snacks before getting up, and regular sips of water may help. If you cannot keep fluids down, feel faint, or are losing weight, contact your clinician promptly.'},{terms:['food','eat','avoid','diet','raw','sushi','cheese'],answer:'A balanced diet with plenty of fluids is a good foundation. Common food-safety guidance includes avoiding raw or undercooked foods, unpasteurised dairy, and high-mercury fish. Your clinician can tailor advice to your health and local guidance.'},{terms:['appointment','doctor','checkup','check-up','questions','midwife'],answer:'You could ask about your baby’s growth, screening options, supplements, symptoms you are noticing, movement changes, birth planning, and when to call urgently. Writing questions down beforehand can make the visit feel easier.'},{terms:['pain','cramp','cramping','back','headache'],answer:'Mild aches can happen as your body changes, but new, severe, persistent, or worsening pain should be discussed with your maternity team. Seek urgent help if pain comes with bleeding, fluid loss, fever, fainting, or trouble breathing.'},{terms:['movement','kick','kicking','baby moving'],answer:'Movements vary by stage and by baby. If you notice a clear change from your baby’s usual pattern, contact your maternity unit or clinician straight away for advice rather than waiting for the next day.'},{terms:['sleep','tired','fatigue','rest'],answer:'Rest when you can, keep regular meals and fluids nearby, and ask for practical support. Persistent exhaustion, dizziness, breathlessness, or low mood deserves a conversation with your care team.'}];
aiAnswers.unshift({terms:['stomach ache','stomachache','stomach pain','belly ache','belly pain','tummy ache','abdominal pain','lower abdominal','upper abdominal'],answer:['A mild stomach or abdominal ache can happen as your body changes, from stretching ligaments, gas, constipation, or muscle strain. Rest, sip water, and notice whether it improves. Contact your maternity team today if it is persistent, worsening, one-sided, or worrying you. Seek urgent help if it comes with bleeding, fluid loss, fever, faintness, severe pain, or regular tightening.','I’m sorry you’re uncomfortable. Gentle rest, hydration, and noticing whether the ache changes with movement, meals, or bowel movements may help you describe it to your clinician. Pregnancy pain that is severe, persistent, one-sided, or accompanied by bleeding, fluid loss, fever, faintness, or contractions needs prompt medical advice.']});
aiAnswers.unshift({terms:['constipation','constipated','bloating','gas'],answer:'Constipation and gas are common in pregnancy. Fluids, fibre-rich foods, gentle movement, and smaller regular meals may help. Check with your clinician before taking a laxative, and seek advice if pain is severe, persistent, or comes with vomiting, fever, bleeding, or inability to pass stool or gas.'});
aiAnswers.unshift({terms:['heartburn','acid reflux','indigestion','burning chest'],answer:'Heartburn is common in pregnancy. Smaller meals, staying upright after eating, and avoiding foods that trigger it may help. Ask your clinician or pharmacist which pregnancy-safe treatment is right for you, especially if symptoms are frequent or severe.'});
aiAnswers.unshift({terms:['raw mango','raw mangoes','kachcha aam','kaccha aam'],answer:'Yes, raw mango is generally okay during pregnancy when it is washed well and eaten in moderation. Choose freshly prepared mango rather than unwashed or pre-cut fruit from an uncertain source. It can be sour and may worsen acidity or heartburn, so stop if it makes you uncomfortable. If you have gestational diabetes or another condition with dietary restrictions, check your portion with your clinician.'});
function aiReply(question){const query=question.toLowerCase().trim();const datasetMatch=pregnancyKnowledge.find(item=>[item.question,...(item.variants||[])].some(phrase=>query===phrase.toLowerCase()||query.includes(phrase.toLowerCase())||phrase.toLowerCase().includes(query)));if(datasetMatch)return datasetMatch.answer;const match=aiAnswers.find(item=>item.terms.some(term=>query.includes(term)));const answer=match?.answer;return Array.isArray(answer)?answer[Math.floor(Math.random()*answer.length)]:answer||'I can help with symptoms, food safety, appointments, movement, rest, and preparing for birth. Tell me what you are noticing, how long it has been happening, and how far along you are. For severe or worrying symptoms, contact your maternity team.'}
function addAiMessage(text,type){const message=document.createElement('div');message.className=`ai-message ai-message-${type}`;message.textContent=text;aiMessages.append(message);aiMessages.scrollTop=aiMessages.scrollHeight}
const aiHistory=[];
async function askAanchal(question){const cleanQuestion=question.trim();if(!cleanQuestion)return;addAiMessage(cleanQuestion,'user');aiHistory.push({role:'user',content:cleanQuestion});aiInput.value='';aiInput.disabled=true;const typing=document.createElement('div');typing.className='ai-message ai-message-bot ai-typing';typing.textContent='Aanchal is thinking...';aiMessages.append(typing);aiMessages.scrollTop=aiMessages.scrollHeight;let response='';try{const result=await fetch(window.AANCHAL_AI_ENDPOINT||'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:aiHistory})});if(!result.ok)throw new Error('AI endpoint unavailable');const data=await result.json();response=data.reply||'';if(!response)throw new Error('AI response empty')}catch(error){response=aiReply(cleanQuestion)}typing.remove();aiInput.disabled=false;addAiMessage(response,'bot');aiHistory.push({role:'assistant',content:response});aiInput.focus()}
const aiChat=document.querySelector('#aiChat'),aiLauncher=document.querySelector('.ai-launcher');
function openAi(){document.body.classList.add('ai-open');aiChat.setAttribute('aria-hidden','false');aiInput.focus()}
function closeAi(){document.body.classList.remove('ai-open');aiChat.setAttribute('aria-hidden','true');aiLauncher.focus()}
aiLauncher.onclick=openAi;document.querySelector('.ai-close').onclick=closeAi;aiForm?.addEventListener('submit',event=>{event.preventDefault();askAanchal(aiInput.value)});document.querySelectorAll('.ai-prompts button').forEach(button=>button.addEventListener('click',()=>askAanchal(button.dataset.question)));
const siteNav=document.querySelector('.nav'),careSection=document.querySelector('#care');
document.querySelectorAll('.nav nav a[href^="#"]').forEach(link=>link.addEventListener('click',()=>document.body.classList.remove('nav-open')));
function updateNavVisibility(){if(!siteNav||!careSection)return;siteNav.classList.toggle('nav-hidden',scrollY>=careSection.offsetTop-innerHeight*.55)}
addEventListener('scroll',updateNavVisibility,{passive:true});addEventListener('resize',updateNavVisibility);updateNavVisibility();
const chapterData={expecting:{kicker:'YOUR NEXT SOFT STEP',heading:'Start with a question.',text:'No question is too small. Ask Aanchal AI about a symptom, a feeling, or what comes next.',page:'expecting.html'},preparing:{kicker:'YOUR NEXT SOFT STEP',heading:'Gather with intention.',text:'Build a calmer birth-day plan with the essentials, questions, and support you want close by.',page:'preparing.html'},recovering:{kicker:'YOUR NEXT SOFT STEP',heading:'Let care come to you.',text:'Rest is productive here. Find gentle recovery essentials and guidance for the days that follow.',page:'recovering.html'}};
document.querySelectorAll('.chapter-tab').forEach(tab=>tab.addEventListener('click',()=>{const data=chapterData[tab.dataset.chapter];document.querySelectorAll('.chapter-tab').forEach(item=>{const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-selected',active)});document.querySelector('#chapterKicker').textContent=data.kicker;document.querySelector('#chapterHeading').textContent=data.heading;document.querySelector('#chapterText').textContent=data.text;document.querySelector('#chapterPackage').href=data.page}));document.querySelectorAll('[data-open-ai]').forEach(button=>button.addEventListener('click',openAi));
